site_name: decijax
site_description: Documentation for the decijax library.
repo_url: https://github.com/Thomas-Christie/decijax
site_url: https://thomas-christie.github.io/decijax/
repo_name: Thomas-Christie/decijax

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.sections
    - navigation.top
    - content.code.copy

plugins:
  - search
  - gen-files:
      scripts:
        - docs/scripts/convert_examples.py
        - docs/scripts/gen_api.py
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: google
            show_root_heading: true
            show_source: false
            show_symbol_type_toc: true
            show_symbol_type_heading: true
            show_signature_annotations: true
            separate_signature: true
            signature_crossrefs: true
            merge_init_into_class: true
            members_order: source
            docstring_section_style: list
            filters:
              - "!^_"
              - "^__init__$"
              - "^__call__$"

nav:
  - 🏡 Home: index.md
  - 💡 Background:
      - Intro to Bayesian Optimisation: _examples/intro_to_bo.md
  - 📕 Reference: api/

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
